---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zqzhou.
--- DateTime: 2019/7/4 下午12:51
---
local string = string
local gsub = string.gsub
local setmetatable = setmetatable
local ngx_encode_base64 = ngx.encode_base64

local keycloak_paths = {
    keycloak_auth_path = "/auth/realms/${realms}/protocol/openid-connect/auth",
    keycloak_token_path = "/auth/realms/${realms}/protocol/openid-connect/token",
    keycloak_session_path = "/auth/admin/realms/${realms}/sessions/${session_id}",
    keycloak_clients_path = "/auth/admin/realms/${realms}/clients",
    keycloak_client_secret_path = "/auth/admin/realms/${realms}/clients/${client_uid}/client-secret",
    keycloak_resources_path = "/auth/admin/realms/${realms}/clients/${client_uid}/authz/resource-server/resource",
}

local MASTER = "master"

local REGEX = "$%{.*%}"
local S_REGEX = "$%{.-%}"

local _M = {}

_M.__index = _M

--- 实例化配置类
--
-- 占位符未替换
function _M:new(conf)
    local configuration = {

        kong_redirect_url = conf.kong_host .. conf.kong_redirect_path,

        kong_client_id = conf.kong_client_id,
        kong_client_secret = conf.kong_client_secret,

        keycloak_admin_uname = conf.keycloak_admin_uname,
        keycloak_admin_pwd = conf.keycloak_admin_pwd,

        keycloak_auth_url = conf.keycloak_host .. keycloak_paths.keycloak_auth_path,
        keycloak_token_url = conf.keycloak_host .. keycloak_paths.keycloak_token_path,
        keycloak_session_url = conf.keycloak_host .. keycloak_paths.keycloak_session_path,
        keycloak_clients_url = conf.keycloak_host .. keycloak_paths.keycloak_clients_path,
        keycloak_client_secret_url = conf.keycloak_host .. keycloak_paths.keycloak_client_secret_path,
        keycloak_resources_url = conf.keycloak_host .. keycloak_paths.keycloak_resources_path
    }

    return setmetatable(configuration, _M)
end

--- 认证地址
--
-- @param realms
-- @return 认证地址
function _M:get_keycloak_auth_url(realms)
    return gsub(self.keycloak_auth_url, REGEX, realms)
end

--- 令牌地址
--
-- @param realms
-- @return 令牌地址
function _M:get_keycloak_token_url(realms)
    return gsub(self.keycloak_token_url, REGEX, realms)
end

--- 会话地址
--
-- @param realms
-- @param session_id
-- @return 会话管理地址
function _M:get_keycloak_session_url(realms, session_id)
    local keycloak_session_url = gsub(self.keycloak_session_url, S_REGEX, realms, 1)
    return gsub(keycloak_session_url, S_REGEX, session_id, 1)
end

--- 客户端地址
--
-- @param realms
-- @return 客户端地址
function _M:get_keycloak_clients_url(realms)
    return gsub(self.keycloak_clients_url, REGEX, realms)
end

--- 客户端资源地址
--
-- @param realms
-- @param client_uid
-- @return 客户端资源地址
function _M:get_keycloak_resources_url(realms, client_uid)
    local keycloak_resources_url = gsub(self.keycloak_resources_url, S_REGEX, realms, 1)
    return gsub(keycloak_resources_url, S_REGEX, client_uid, 1)
end

--- 客户端秘钥地址
--
-- @param realms
-- @param client_uid
-- @return 客户端资源地址
function _M:get_keycloak_client_secret_url(realms, client_uid)
    local keycloak_client_secret_url = gsub(self.keycloak_client_secret_url, S_REGEX, realms, 1)
    return gsub(keycloak_client_secret_url, S_REGEX, client_uid, 1)
end

--- 获取kong客户端的凭证
--
-- @param 插件配置
function _M:get_kong_client_credentials()
    return ngx_encode_base64(self.kong_client_id .. ":" .. self.kong_client_secret)
end

--- 获取完整配置
--
-- @param 插件配置
-- @return 包含 重定向地址、认证地址、令牌地址和客户端地址
function _M:configurations(x_realms)
    return {
        realms = x_realms or MASTER,
        kong_redirect_url = self.kong_redirect_url,
        keycloak_auth_url = self:get_keycloak_auth_url(x_realms or MASTER),
        keycloak_token_url = self:get_keycloak_token_url(x_realms or MASTER),
        keycloak_clients_url = self:get_keycloak_clients_url(x_realms or MASTER),

        kong_client_id = self.kong_client_id,
        kong_client_secret = self.kong_client_secret,
        kong_client_credentials = self:get_kong_client_credentials(),

        keycloak_admin_uname = self.keycloak_admin_uname,
        keycloak_admin_pwd = self.keycloak_admin_pwd,
    }
end

return _M